name: Contains and value
on:
  pull_request:

permissions:
  contents: read

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo ${{ contains(github.ref, 'refs/pull/') && github.head_ref }}
