name: One named secret
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "building"
