name: All secrets in the environment
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          ALL_SECRETS: ${{ toJSON(secrets) }}
        run: echo "building"
