name: Composite caller
on:
  pull_request:

permissions:
  contents: read

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        uses: ./.github/actions/greet
        with:
          title: ${{ github.event.pull_request.title }}
